# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build, Test & Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          secrets: |
            ACCESS_CONTROL_ALLOW_ORIGIN
            FROM_EMAIL
            MAIL_SUBJECT
            MAILGUN_API_KEY
            MAILGUN_API_BASE_URL
            MAILGUN_TEMPLATE
            RECAPTCHA_SECRET
            RECIPIENT_EMAIL
            SENTRY_DSN
        env:
          ACCESS_CONTROL_ALLOW_ORIGIN: ${{ secrets.CF_ACCESS_CONTROL_ALLOW_ORIGIN }}
          FROM_EMAIL: ${{ secrets.CF_FROM_EMAIL }}
          MAIL_SUBJECT: ${{ secrets.CF_MAIL_SUBJECT }}
          MAILGUN_API_KEY: ${{ secrets.CF_MAILGUN_API_KEY }}
          MAILGUN_API_BASE_URL: ${{ secrets.CF_MAILGUN_API_BASE_URL }}
          MAILGUN_TEMPLATE: ${{ secrets.CF_MAILGUN_TEMPLATE }}
          RECAPTCHA_SECRET: ${{ secrets.CF_RECAPTCHA_SECRET }}
          RECIPIENT_EMAIL: ${{ secrets.CF_RECIPIENT_EMAIL }}
          SENTRY_DSN: ${{ secrets.CF_SENTRY_DSN }}
